version: '3'
services:
  demo-app:
    build: .
    volumes:
      - /src/.venv
      - .:/src
    ports:
      - 8000:8000  # ホストマシンのポート8000を、docker内のポート8000に接続する
    environment:
      - WATCHFILES_FORCE_POLLING=true  # 環境によってホットリロードのために必要

